app/urls.py
from django.urls import path
from .views import home, blog_category, category, blog_detail, add_blog, blog_update, blog_delete, user_list, my_blog, blog_tag
app_name = 'app'

urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:slug>', blog_category, name='blog_category'),
    path('my-blog/', my_blog, name='my_blog'),
    path('blog-detail/<slug:slug>', blog_detail, name='blog_detail'),
    path('category-list/', category, name='category-list'),
    path('add-blog/', add_blog, name='add_blog'),
    path('blog-update/<slug:slug>', blog_update, name='blog_update'),
    path('blog-delete/<slug:slug>', blog_delete, name='blog_delete'),
    path('user-list/', user_list, name='user_list'),
    path('blog_-ag/<slug:slug>', blog_tag, name='blog_tag'),

]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/add_blog.html
{% extends 'base.html' %}

{% block title %}Add blog{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Blog</button>
</form>

{% endblock %}

templates/app/blog_delete.html
{% extends 'base.html' %}

{% block title %}Update blog{% endblock %}

{% block content %}

<div class="main">
    <form method="POST">
        {% csrf_token %}
        Siz bu blogni o'chirmoqchimisiz
        <input type="submit" class="btn btn-danger" value="Yes" />
        <a href="{% url 'app:blog_detail' blog.slug %}"><button type="button" class="btn btn-warning">Cancel</button></a>
    </form>
</div>

{% endblock %}

templates/app/blog_detail.html
{% extends 'base.html' %}

{% block title %}{{ blog.title }}{% endblock %}

{% block content %}

    <hr>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <span>Sana: {{ blog.created | time:'h:i' }} / {{ blog.created|date:'d.m.Y' }}  | Author: {{ blog.author.username }} | </span>
            <span> Ko'rish: {{ blog.view }}</span>
            <h2>{{ blog.title }}</h2>
            <div><img style="width: 80%;" src="{{ blog.image.url }}"></div>

            <p>{{ blog.text }}</p>
            {% for tag in blog.tags.all %}
            <a href="{% url 'app:blog_tag' tag.slug %}"> #{{ tag.name }}  | </a>
            {% endfor %}
            <hr>
            {% if user == blog.author %}
            <p>
            <a href="{% url 'app:blog_update' blog.slug %}" class="btn btn-success" >Update</a>
            <a href="{% url 'app:blog_delete' blog.slug %}" class="btn btn-danger" >Delete</a>
            </p>
            {% endif %}
            {% if user.is_authenticated %}
            <hr>
            <div class="row">
                <div class="col-6">
                    {% for comment in blog.comment.all %}
                    <p>{{ comment.user.username }}</p>
                    <p>{{ comment.text }}</p>
                    <hr>
                    {% endfor %}
                </div>
                <div class="col-6">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p  }}
                        <button  type="submit" >Add comment</button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/app/blog_update.html
{% extends 'base.html' %}

{% block title %}Update blog{% endblock %}

{% block content %}
<h2>{{ blog.author }} ga tegishli blog</h2>

<form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update Blog</button>
</form>

{% endblock %}

templates/app/category.html
{% extends 'base.html' %}

{% block title %} category {% endblock %}

{% block content %}
    
       <h1>All Category</h1>
{% for category in categories %}
    <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ category.image.url }}" class="img-fluid rounded-start" alt="..." style="width: 150px">
    </div>
    <div class="col-md-8">
      <div class="card-body">

        <h5 class="card-title"><a href="{% url 'app:blog_category' category.slug %}">{{ category.name }}</a> | {{ category.blog.count }}</h5>
        <p class="card-text">{{ category.text }}</p>
      </div>
    </div>
  </div>
</div>

{% endfor %}
{% endblock %}

templates/app/home.html
{% extends 'base.html' %}

{% block title %}{% if category %} {{ category.name }}{% else %} Blog {% endif %}{% endblock %}

{% block content %}

    <h1>All blogs</h1>
    {% for blog in blogs %}
        <div class="card" style="width: 60%">
            <div class="card-body">
                <a href="{% url 'app:blog_detail' blog.slug %}"  style="text-decoration: none;"><h5 style="color:#18bc9c;" class="card-title">{{ blog.title }}</h5></a>
                <p class="card-text"><a  style="text-decoration: none; color: black"><i class="fa-solid fa-star"></i>{{ blog.category }}</a>
                &nbsp;<small class="text-muted">Author: {{ blog.author.username }}  Date: {{ blog.created|date:'d-m-y/H:i' }}</small></p>
                <img style="height: 400px" src="{{ blog.image.url }}" class="card-img-bottom" alt="...">
                <p class="card-text">{{ blog.text|truncatewords:10|safe }}</p>
                <p class="card-text">
                      <small class="text-muted"><i class="fa-solid fa-user"></i> {{ blog.user.username }}</small>
                    {% for tag in blog.tags.all %}
                        <a class="text-muted">{{ tag.name }}</a>
                    {% endfor %}
                <small class="text-muted" style="padding-left: 500px" >
                     <i class="fa-solid fa-eye"></i> {{ blog.views }}
                </small>

                </p>
            </div>
        </div>
        <p></p>
    {% endfor %}
    <hr>
    {% if blogs.has_previous %}
        <a href="?page={{ blogs.previous_page_number }}">Back</a>
    {% endif %}
    {% for l in  blogs.page_range %}
        <li><a href="?page={{forloop.counter}}">{{ forloop.counter }}</a></li>
    {% endfor %}
    {% if blogs.has_next %}
        <a href="?page={{ blogs.next_page_number }}">Next</a>
    {% endif %}

{% endblock %}

templates/app/my_blog.html
{% extends 'base.html' %}

{% block title %}My blogs{% endblock %}

{% block content %}

    <h1>All blogs</h1>
    {% for blog in blogs %}
        <div class="card" style="width: 60%">
            <div class="card-body">
                <a href="{% url 'app:blog_detail' blog.slug %}"  style="text-decoration: none;"><h5 style="color:#18bc9c;" class="card-title">{{ blog.title }}</h5></a>
                <p class="card-text"><a  style="text-decoration: none; color: black"><i class="fa-solid fa-star"></i>{{ blog.category }}</a>
                &nbsp;<small class="text-muted">Author: {{ blog.author.username }}  Date: {{ blog.created|date:'d-m-y/H:i' }}</small></p>
                <img style="height: 400px" src="{{ blog.image.url }}" class="card-img-bottom" alt="...">
                <p class="card-text">{{ blog.text|truncatewords:10|safe }}</p>
                <p class="card-text">
                      <small class="text-muted"><i class="fa-solid fa-user"></i> {{ blog.user.username }}</small>
                    {% for tag in blog.tags.all %}
                        <a class="text-muted">{{ tag.name }}</a>
                    {% endfor %}
                <small class="text-muted" style="padding-left: 500px" >
                     <i class="fa-solid fa-eye"></i> {{ blog.views }}
                </small>

                </p>
            </div>
        </div>
        <p></p>
    {% endfor %}
    <hr>
    {% if blogs.has_previous %}
        <a href="?page={{ blogs.previous_page_number }}">Back</a>
    {% endif %}
    {{ blogs.number }}
    {% if blogs.has_next %}
        <a href="?page={{ blogs.next_page_number }}">Next</a>
    {% endif %}

{% endblock %}

templates/app/user_list.html
{% extends 'base.html' %}

{% block title %}{% if category %} {{ category.name }}{% else %} Blog {% endif %}{% endblock %}

{% block content %}
<form method="get">
    <input type="text", name="search">
    <button type="submit">Search</button>
</form>
<div class="row">
            <div class="col-3">Username</div>
            <div class="col-3">First name</div>
            <div class="col-3">Last login</div>
            <div class="col-3">Date join</div>
        </div>
    {% for user in users %}
        <div class="row">
            <div class="col-3">{{ user.username }}</div>
            <div class="col-3">{{ user.first_name }}</div>
            <div class="col-3">{{ user.last_login }}</div>
            <div class="col-3">{{ user.date_joined }}</div>
        </div>
    {% endfor %}
{% endblock %}