app/urls.py
from django.urls import path
from .views import home, blog_category, category, blog_detail, add_blog, blog_update, blog_delete, user_list, my_blog, blog_tag
app_name = 'app'

urlpatterns = [
    path('', home, name='home'),
    path('category/<slug:slug>', blog_category, name='blog_category'),
    path('my-blog/', my_blog, name='my_blog'),
    path('blog-detail/<slug:slug>', blog_detail, name='blog_detail'),
    path('category-list/', category, name='category-list'),
    path('add-blog/', add_blog, name='add_blog'),
    path('blog-update/<slug:slug>', blog_update, name='blog_update'),
    path('blog-delete/<slug:slug>', blog_delete, name='blog_delete'),
    path('user-list/', user_list, name='user_list'),
    path('blog_-ag/<slug:slug>', blog_tag, name='blog_tag'),

]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('user.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import login_view, logout_view, register

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('register/', register, name='register'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'navbar.html' %}
</header>
<div class="container">
  <div class="row">
    <div class="col-9">
        {% block content %}

        {% endblock %}
    </div>
    <div class="col-3">
        {% include 'saidbar.html' %}
    </div>
  </div>
     <div class="footer-basic d-flex justify-content-end    ">
        <footer>
            <div class="social"><a href="#"><i class="fa-brands fa-instagram"></i></a><a href="#"><i class="fa-brands fa-telegram"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a
                    href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Company Name © 2022</p>
        </footer>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<div class="container">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'app:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:category-list' %}">Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:user_list' %}">Foyfalanuvchilar</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:my_blog' %}">My Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:add_blog' %}">Add Blog</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.username }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'user:logout_view' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login_view' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
  <div class="row">
    <div class="col-12" >
      {% if messages %}
        {% for mess in messages %}
        <p>{{ mess }}</p>
        {% endfor %}
      {% endif %}
    </div>
  </div>
</div>

templates/saidbar.html
<p class="text-info">Bloglar</p>
{% for category in categories %}
    <p><a href="{% url 'app:blog_category' category.slug %}" >{{ category.name }}</a></p>
{% endfor %}
<p>All Tags</p>
<div class="row">
    <div class="col-12">
        {% for tag in tags %}
            <a href="" >{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>